[general]
chat_models = ["gpt-3.5-turbo", "gpt-4"]
model = "gpt-4"
temperature = 0

[prompts]
instruction_prompt = """
Classify the sentiment of each conversation in >>>>>CONTENT<<<<<
as "negative" and "positive".
Return the output as valid JSON.

Follow these steps when classifying the conversations:
1. Does the customer use swear words or ðŸ˜¤?
2. Does the customer seem aggravated or angry?

If you answer "Yes" to one of the above questions,
then classify the conversation as "negative".
Otherwise classify the conversation as "positive".

Let's think step by step

#### START EXAMPLES

------ Example Inputs ------
[Agent] 2023-07-24 : What can I help you with?
[Customer] 2023-07-24 : I CAN'T CONNECT TO MY ðŸ˜¤ ACCOUNT
[Agent] 2023-07-24 : Are you sure it's not your caps lock?
[Customer] 2023-07-24 : ðŸ˜¤! You're right!
   - Does the customer use swear words or ðŸ˜¤? Yes
   - Does the customer seem aggravated or angry? Yes
   - Sentiment: "negative"

[Agent] 2023-06-15 : Hello! How can I assist you today?
[Customer] 2023-06-15 : I can't seem to find the download link for my purchased software.
[Agent] 2023-06-15 : No problem, ****. Let me find that for you. Can you please provide your order number?
[Customer] 2023-06-15 : It's ****. Thanks for helping me out!
   - Does the customer use swear words or ðŸ˜¤? No
   - Does the customer seem aggravated or angry? No
   - Sentiment: "positive"

------ Example Output ------

{
  "negative": [
    {
      "date": "2023-07-24",
      "conversation": [
        "A: What can I help you with?",
        "C: I CAN'T CONNECT TO MY ðŸ˜¤ ACCOUNT",
        "A: Are you sure it's not your caps lock?",
        "C: ðŸ˜¤! You're right!"
      ]
    }
  ],
  "positive": [
    {
      "date": "2023-06-15",
      "conversation": [
        "A: Hello! How can I assist you today?",
        "C: I can't seem to find the download link for my purchased software.",
        "A: No problem, ****. Let me find that for you. Can you please provide your order number?",
        "C: It's ****. Thanks for helping me out!"
      ]
    }
  ]
}

#### END EXAMPLES
"""

role_prompt = """You are a thoroughly trained machine learning
model that is an expert at sentiment classification.
You diligently complete tasks as instructed.
You never make up any information that isn't there."""

positive_example = """
"""
positive_reasoning = """
"""
positive_output = """
"""
negative_example = """
"""
negative_reasoning = """
"""
negative_output = """
"""
